# Generated by Django 6.0.2 on 2026-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='operator_role',
            field=models.CharField(blank=True, choices=[('lighting', 'Lighting'), ('sound', 'Sound'), ('stage', 'Stage')], max_length=30, null=True),
        ),
    ]
