# Generated by Django 6.0.2 on 2026-02-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_operator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cue',
            name='cue_type',
            field=models.CharField(choices=[('lighting', 'Lighting'), ('sound', 'Sound'), ('stage', 'Stage')], max_length=30),
        ),
    ]
