# Generated by Django 6.0.2 on 2026-03-01 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cue_cue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cue',
            name='cue_type',
        ),
        migrations.AddField(
            model_name='cue',
            name='cue_date',
            field=models.DateField(default=datetime.date(2026, 3, 1)),
            preserve_default=False,
        ),
    ]
