# Generated by Django 6.0.2 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_complaint_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply_seen',
            field=models.BooleanField(default=False),
        ),
    ]
