# Generated by Django 6.0.2 on 2026-03-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_record', to='core.attendance'),
        ),
    ]
