# Generated by Django 6.0.2 on 2026-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_salary_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('operator', 'Operator'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
