# Generated by Django 6.0.2 on 2026-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cue',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
