# Generated by Django 6.0.2 on 2026-03-30 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cue',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cue',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_cues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cue',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cue',
            name='backup_operators',
            field=models.ManyToManyField(blank=True, related_name='backup_cues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cue',
            name='escalation_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('primary', 'Primary Alert'), ('backup', 'Backup Alert'), ('admin', 'Admin Alert')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
